name: langchain_google
description: LangChain.dart integration module for Google (VertexAI, PaLM, Matching Engine, etc.).
version: 0.2.4+1
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_google
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:langchain_google
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

topics:
  - ai
  - nlp
  - llms
  - langchain
  - vertex-ai

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ">=1.17.0 <1.19.0"
  gcloud: ^0.8.12
  googleai_dart: ^0.0.3
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  langchain: ^0.4.2
  meta: ^1.9.1
  uuid: ^4.0.0
  vertex_ai: ^0.0.10

dependency_overrides:
  vertex_ai:
    git:
      url: https://github.com/orenagiv/langchain_dart.git
      path: packages/vertex_ai
      ref: main

dev_dependencies:
  test: ^1.25.2
